FROM node:latest
WORKDIR /anna
RUN apt-get update && \
apt-get install -y nginx
COPY tpt_exam/exam_php/ ./
#RUN npm install && npm run ng build -- --output-path=/var/www/html
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
